site_name: Angular localization
nav:
- Home: 'index.md'
nav:
  - Home: index.md
  - Quick start: quick-start.md
  - Specification:
    - Library structure: spec/library-structure.md
    - Configuration: spec/configuration.md
    - Getting the translation: spec/getting-the-translation.md
    - Lazy loaded modules & Shared modules: spec/lazy-loading.md
    - Validation by locales: spec/validation.md
    - Collator: spec/collator.md
    - SEO by locales: spec/seo.md
    - Setting the locale in Accept-Language header: spec/interceptor.md
    - Unit testing: spec/testing.md
    - Services APIs: spec/api.md
repo_url: https://github.com/robisim74/angular-l10n
repo_name: 'GitHub'
site_description: 'An Angular library to translate messages, dates and numbers'
site_author: 'Roberto Simonetti'
markdown_extensions:
  - toc:
      permalink: true
theme:
  name: 'material'
  palette:
    primary: 'indigo'
    accent: 'indigo'
extra:
  social:
    - type: 'github'
      link: 'https://github.com/robisim74'
    - type: 'twitter'
      link: 'https://twitter.com/robisim74'